# Site settings
title: Here I go again.
header-img: img/home-bg.png
email: brymcafee@gmail.com
copyright_name: bryanmcafee
description: > # this means to ignore newlines until "baseurl:"
  Heading back to school for career change. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bryanmcafee
learn_profile: bryanmcafee
email_username: brymcafee@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
